# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
url:              http://theme.authentiq.io/
encoding:         UTF-8

# Custom vars
current_version:  3.3.7aq1
repo:             https://github.com/AuthentiqID/bootstrap
sass_repo:        https://github.com/twbs/bootstrap-sass

download:
  source:         https://github.com/AuthentiqID/bootstrap/archive/v3.3.7aq1.zip
  dist:           https://github.com/AuthentiqID/bootstrap/releases/download/v3.3.7aq1/bootstrap-3.3.7aq1-dist.zip
  sass:           https://github.com/twbs/bootstrap-sass/archive/v3.3.7aq1.tar.gz

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com

cdn:
  css:            https://cdn.authentiq.io/theme/3.3.7aq1/css/authentiq-bootstrap.min.css
  css_theme:      https://cdn.authentiq.io/theme/3.3.7aq1/css/authentiq-bootstrap-theme.min.css
  js:             https://cdn.authentiq.io/theme/3.3.7aq1/js/authentiq-bootstrap.min.js
